import styles from './heroBanner.module.scss'

export default function HeroBanner() {
  return (
    <div className={styles.heroBanner}>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veniam nulla suscipit delectus aliquam quas blanditiis laudantium ipsam, ab ut illo rem atque deleniti in nobis, sit quaerat corrupti vitae. Nostrum!
      Sunt et vero suscipit hic sint, est possimus eaque mollitia laudantium. Porro dignissimos perferendis vero labore eius qui soluta animi, ad eveniet, blanditiis recusandae nemo? Assumenda, corporis animi. Modi, exercitationem!
      Unde tempore quas voluptatum odio vel, magnam minus mollitia nisi molestias magni voluptates voluptatibus qui blanditiis nam deleniti obcaecati, minima labore quis adipisci accusamus. Omnis temporibus illo magni quam voluptas!
      Saepe quod soluta suscipit ratione, omnis explicabo totam alias ipsam fugit quae distinctio consectetur qui quos? Quis, qui facilis! Voluptates porro iure nesciunt eos tempora vitae ut, hic nisi modi.
      Quasi asperiores quaerat architecto recusandae alias corporis repellendus rem rerum. Amet necessitatibus inventore quo facere similique in repellendus, sit earum autem, ullam molestiae modi alias optio quae quidem voluptatem rem.
      Velit, nam. Harum nihil dolorum perspiciatis. Aliquam omnis exercitationem vitae? Nihil, accusamus amet saepe sunt doloribus nulla corrupti sequi a nesciunt eligendi, voluptate cupiditate? Voluptatem delectus unde rerum doloremque accusantium.
      Amet quod id magnam ducimus quia, dolorem in voluptatum repudiandae quaerat accusantium cupiditate delectus asperiores sit porro, fuga ipsam. Excepturi mollitia ratione nemo quisquam nobis voluptatum nesciunt sapiente veniam sunt.
      At rem, eos cupiditate magnam quisquam rerum ex dignissimos culpa nam autem, quis numquam voluptatum suscipit atque debitis quam laborum vero temporibus. Libero sequi vitae praesentium, voluptas obcaecati consequuntur quod!
      Totam voluptas tenetur sed facere praesentium, aperiam ad reprehenderit excepturi repellendus eum laborum delectus quidem rem esse cumque optio odio fuga in dolor laboriosam enim dolorem quo obcaecati! Ipsam, ex?
      Fugit ipsam maiores officia placeat repellat ut suscipit praesentium sequi minus inventore. Cum facere, expedita tempora ullam quibusdam asperiores nihil accusamus earum eius aut veniam tempore quis hic saepe architecto?
      Iste, aliquam itaque molestias, excepturi praesentium dolore, quis quibusdam porro velit facere eius repellat reprehenderit sit dicta maiores consequuntur? Ducimus magnam temporibus optio commodi explicabo dignissimos. Aut magnam id eaque.
      Voluptates deleniti dignissimos nemo mollitia consequatur, ducimus vero ad quas quaerat perferendis quae sequi non molestias sint deserunt odit ut reiciendis quasi aspernatur tempore reprehenderit cupiditate nisi eum recusandae. Natus?
      Aperiam repudiandae incidunt minima omnis fuga saepe recusandae neque? Quo, recusandae, doloribus aperiam, mollitia culpa ab nobis explicabo tempora perferendis delectus dicta molestias tempore quam! Illo dolore voluptatum ea unde.
      Repudiandae culpa excepturi accusantium iure, reiciendis ducimus, reprehenderit earum quidem inventore aut similique, assumenda laborum maiores! Recusandae, minima praesentium. Molestiae distinctio officiis earum est delectus sequi praesentium vel exercitationem quis!
      Quis reprehenderit expedita necessitatibus atque aspernatur quibusdam omnis repudiandae unde ab. Tenetur, nulla earum, eos saepe quos beatae explicabo totam dicta eveniet suscipit adipisci cum odio dolor. Sapiente, laboriosam aperiam?
      Id illo est placeat nesciunt repellat voluptas eligendi perferendis molestias blanditiis modi quos earum doloribus facilis, magni suscipit doloremque libero sunt assumenda accusamus voluptatibus vel explicabo eveniet natus dolorum. Earum.
      Pariatur quaerat perspiciatis fugit cum aliquam, obcaecati soluta deserunt magnam reprehenderit neque. Vero iste voluptates beatae voluptatem perferendis earum non tempora obcaecati magni odit vel hic maiores inventore, laboriosam explicabo.
      Laboriosam beatae dicta natus corporis facere amet iste neque, adipisci nihil fugiat autem recusandae blanditiis numquam inventore aperiam consequatur dolorem culpa provident qui quis. Nostrum sit distinctio neque optio maiores!
      Consequatur ut eveniet rerum in unde distinctio quas veniam voluptatibus illo sapiente nulla iure excepturi voluptas ex dolores repellat et asperiores, numquam quibusdam est necessitatibus at delectus. Ipsa, reiciendis illo.
      Sunt fugit repellendus possimus rerum, esse corporis quae, alias ipsam eum amet, dolores cupiditate deleniti enim quidem fugiat aut minus vitae magni dolor! Esse quibusdam ea atque nam dolore impedit.
      Reprehenderit repellendus ex labore ea hic optio autem consequatur amet deserunt delectus tempore, architecto consectetur praesentium expedita iste, laboriosam, aliquid illum vero repudiandae! Enim, tempora ea. Quas natus velit non?
      Dicta mollitia exercitationem minima placeat quam quas deleniti odit sequi adipisci repudiandae eveniet qui corrupti asperiores ipsa excepturi, illo veniam similique. Quibusdam, repellendus consequuntur. Et sit autem ipsam sint officiis!
      Quisquam eaque voluptate ullam ipsa cupiditate dicta labore praesentium aliquam quo minus, non maxime excepturi molestias consequuntur quaerat! Officia voluptatum aliquam, id nobis consequuntur doloribus assumenda! Odit porro doloribus a.
      Ab, repellat eius qui aliquid in porro impedit eos sit consectetur optio aspernatur deserunt et dolorem illo. Id veniam eaque, unde repudiandae, voluptates in omnis illum exercitationem vitae, nulla quasi.
      Qui dolor harum et, quibusdam excepturi eos impedit hic ratione nam, molestias perspiciatis labore cupiditate quos dolore autem quae totam modi esse nemo tenetur assumenda? Commodi necessitatibus unde vitae consequuntur.
      Suscipit a fugiat distinctio veniam hic minus veritatis officiis excepturi cumque aperiam expedita assumenda labore, recusandae quis dolores reiciendis iste libero maxime optio voluptate sed aspernatur tempora quos vitae. Nobis.
      Voluptatum qui quibusdam earum nobis soluta commodi amet esse perspiciatis placeat blanditiis est, eligendi, a, tempore neque debitis et velit. Nemo fugit aut perferendis dolores! Facere fugiat alias quis voluptatibus.
      At pariatur quia perspiciatis voluptas assumenda doloremque maiores, consequuntur totam cum facilis, eos praesentium, id explicabo itaque ullam dolores debitis incidunt voluptatem aperiam dolor? Ea voluptatem fuga voluptatum soluta culpa.
      Rerum expedita nostrum sint possimus cupiditate dicta dolore voluptates, non unde, quibusdam ipsam id ipsum ullam libero enim incidunt perferendis quaerat amet ducimus totam, debitis accusamus animi provident! Consectetur, officia.
      Debitis et at, placeat ducimus nesciunt earum aperiam, voluptates atque modi in quibusdam obcaecati, excepturi quis? Dignissimos suscipit aliquam enim, error sed laudantium harum doloribus! Temporibus distinctio tempore et amet.
      Aut unde, cum debitis quae vel reiciendis doloremque, sapiente, id ipsum aliquid qui tempore ad fugiat et quibusdam dolorum accusamus voluptas deleniti cumque vitae illo? Sed nihil iste quaerat cupiditate.
      Dicta eius nobis dolorem aliquid, id doloremque labore, perferendis animi aperiam magnam illum odio. Aut atque ipsa maiores. Non, sapiente nobis amet placeat nesciunt sed sint aliquid doloribus necessitatibus quia!
      Libero beatae eaque nostrum dolor, nulla laudantium sapiente fugit quibusdam blanditiis eius cum soluta corrupti nobis itaque ex reiciendis velit, perferendis excepturi dolorum. Aspernatur est incidunt distinctio nemo ad architecto.
      Dolore corporis amet obcaecati labore. Enim, ex? Necessitatibus voluptates quasi sapiente ipsam! Distinctio, iusto quis quasi quisquam nobis rerum perspiciatis laboriosam, aspernatur odit perferendis fugiat vel labore deserunt sit! Culpa?
      Expedita dolore voluptatum repellat quod voluptatem, praesentium totam numquam esse consequuntur quam nihil, consequatur, eligendi quas placeat repudiandae reprehenderit laborum voluptas enim maiores obcaecati quidem ex. Illum ea illo nesciunt?
      Temporibus, maxime assumenda asperiores perspiciatis quis dignissimos repudiandae nostrum qui blanditiis provident, tempora consequatur laborum totam, illo reiciendis nemo placeat quam corrupti modi? Eligendi, eos. Inventore veniam itaque praesentium neque.
      Unde eligendi libero cumque nesciunt, tenetur quidem recusandae voluptatum ullam reiciendis harum maiores aspernatur exercitationem dolore deserunt voluptate quas repellat cum iure quia corporis voluptates. Distinctio inventore tempora quam eum?
      Repudiandae, qui eligendi nesciunt vel ullam totam ipsam aperiam corrupti at incidunt culpa eius ipsa, architecto eaque ea ratione accusamus itaque, cumque quaerat? Commodi cupiditate quasi asperiores reprehenderit! Exercitationem, ducimus!
      Magnam a sunt odit voluptatibus autem dolor dolore corrupti ipsum hic molestias, similique impedit? Accusantium laborum, aliquam maxime dolorem ducimus odit cum minima perspiciatis? Sunt explicabo harum officiis tempora molestiae.
      Quos et, ea eaque quod sint suscipit quis, non tenetur consectetur, nihil esse? Molestiae fuga magni quaerat est voluptates. Vel facilis asperiores earum consectetur pariatur non ullam incidunt, quisquam alias.
      Omnis quaerat reprehenderit tenetur voluptatum consequuntur corrupti recusandae quas, esse quibusdam consectetur at perspiciatis laudantium et suscipit reiciendis veritatis perferendis deserunt neque! Dolore, deleniti vero consequatur odio laudantium repudiandae quaerat.
      A eaque possimus deleniti ratione officia eligendi nobis alias accusamus, rem dolore assumenda hic. Odit aut delectus molestiae recusandae commodi ratione voluptate hic. Dignissimos quibusdam itaque doloremque. Minima, nesciunt blanditiis.
      Omnis ex ea similique deleniti minus, hic vitae vel nihil modi temporibus reiciendis rem quod fuga illum repellendus nisi accusamus voluptate. Quaerat architecto quam exercitationem nesciunt tempora impedit doloremque repudiandae.
      Error tempore obcaecati dolore praesentium, assumenda nobis repudiandae vero earum ducimus officia ea impedit. Illo animi odit saepe voluptate architecto doloremque exercitationem, dolor nulla, libero iusto placeat praesentium deserunt atque.
      Perspiciatis deleniti nihil nam explicabo corrupti quibusdam a? Saepe deserunt non voluptas expedita cum, eaque sed deleniti ab explicabo repellat molestiae alias laborum culpa est itaque accusantium modi? Adipisci, quo?
      Deleniti deserunt, quod iste esse aliquam voluptate tenetur mollitia. Dignissimos, adipisci doloribus enim fugit reprehenderit quisquam, recusandae libero vitae aliquam hic unde ipsam facere nihil ipsa asperiores dolorem magni earum.
      Beatae dolore ipsa sint omnis modi nesciunt voluptatibus voluptas quibusdam perspiciatis, suscipit ipsam rem quia consequatur. Quae, eum dolorem itaque enim molestiae soluta? Voluptatum, eveniet! Perferendis veniam cumque laborum ducimus?
      Deleniti sit numquam sapiente rem! Placeat, deleniti voluptatum porro inventore unde a consectetur, repellat, recusandae asperiores neque corrupti rerum! Nostrum id et adipisci animi enim libero a, accusamus autem minus?
      Corporis omnis eveniet nobis, odio sed quibusdam, officia soluta, praesentium beatae fugiat distinctio perspiciatis atque eaque? Soluta consectetur illo assumenda saepe aspernatur, cumque autem aliquid omnis tenetur necessitatibus? Doloribus, saepe.
      Culpa, itaque! Nihil sunt consequuntur hic tempora doloribus repellendus rerum modi reprehenderit, accusantium sit, earum, voluptates fugit quod aliquam? Beatae fugit explicabo cum ullam omnis dolorem quia aut, quae assumenda.</p>
    </div>
  )
}
